# This R script plots data from data frames generated by `events_process-data.R`

# Remember it is good coding technique to add additional packages to the top of your script 
library(anytime) # for working with dates
library(scales)   # to access breaks/formatting functions
## tidyverse
library(tidyverse) # load the tidyverse, which includes dplyr, tidyr and ggplot2
library(lubridate) # for working with dates
library(ggrepel)
library(ggthemes) # install themes for ggplots
library(gridExtra) # add graphical objects (grob) to ggplot
library(cowplot) # to arrange plots on a canvas
library(plotly) # interactive plots based on ggplot
#library(readr) # for reading data
# mapping packages
library(sp)
library(rgdal)
#library(geojsonio)
library(maps)  # contains outliens of continents, countries etc. Higher resolution is available from mapdata
library(ggmap)
library(maptools)
# enable unicode
Sys.setlocale("LC_ALL", "en_US.UTF-8")
# set a general theme for all ggplots
theme_set(theme_bw())

# set a working directory
setwd("/BachCloud/BTSync/FormerDropbox/FoodRiots/food-riots_data") #Volumes/Dessau HD/

# read / load data
load("rda/events_food-riots.rda") # loads data.Events.FoodRiots
data.Exports <- read.csv("csv/export-statistics.csv", header=TRUE, sep = ",", quote = "\"")
data.Locations <- read.csv("csv/locations.csv", header=TRUE, sep = ",", quote = "\"") # this file contains toponyms and coordinates

## convert data types
## anydate() converts dates from Y0001 to Y0001-M01-D01
data.Exports$schema.date <- anydate(as.factor(data.Exports$schema.date))
  
## add geo-coordinates based on data.Locations
data.Events.FoodRiots <- data.Events.FoodRiots %>%
  dplyr::left_join(data.Locations,  by =  c("schema.Place" = "schema.Place"))
data.Exports <- data.Exports %>%
  dplyr::left_join(data.Locations,  by =  c("schema.Place" = "schema.Place"))

## clean data
data.Exports <- data.Exports %>%
  dplyr::rename(commodity = commodity.1,
                quantity = quantity.1,
                unit = unit.1,
                currency = unit.2,
                value = quantity.2) %>% # rename the columns relevant to later operations
  dplyr::select(-commodity.2) # omit columns not needed


  
# specify period
## function to create subsets for periods
func.Period.Date <- function(f,x,y){f[f$schema.date >= x & f$schema.date <= y,]}
#func.Period.Year <- function(f,x,y){f[f$year >= x & f$year <= y,]}
date.Start <- anydate("1855-01-01")
date.Stop <- anydate("1916-12-31")
data.Events.FoodRiots.Period <- func.Period.Date(data.Events.FoodRiots,date.Start,date.Stop)
data.Exports.Period <- func.Period.Date(data.Exports, date.Start, date.Stop)

# variable for period as string
period.String <- paste(year(date.Start),"-",year(date.Stop),sep = "")

# specify a geographic region
## Bilād al-Shām
location.Levant <- c('Acre','Aleppo','Baʿbdā','Beirut','Bayrūt','Damascus','Haifa',
                     'Hama','Hebron','Homs','Jaffa','Jerusalem','Nablus','Latakia','Tripoli','Syria')
data.Events.FoodRiots.Period.Levant <- subset(data.Events.FoodRiots.Period, schema.Place %in% location.Levant)


## summarise data
## Levant
data.Events.FoodRiots.Period.Levant.Summary <- data.Events.FoodRiots.Period.Levant %>%
  group_by(schema.Place, schema.latitude, schema.longitude) %>%
  summarise(number.of.events = n()) %>%
  arrange(desc(number.of.events))
## Global
data.Events.FoodRiots.Period.Summary <- data.Events.FoodRiots.Period %>%
  group_by(schema.Place, schema.latitude, schema.longitude) %>%
  summarise(number.of.events = n()) %>%
  arrange(desc(number.of.events))
## Exports by location
data.Exports.Period.Summary.Annual <- data.Exports.Period %>%
  group_by(schema.Place,schema.latitude,schema.longitude, schema.date, commodity, unit, currency) %>%
  summarise(quantity = mean(quantity), # provides the quantity per location, per date, per commodity, per unit and per currency
            value = mean(value)) %>% # same for value
  arrange(schema.Place)
data.Exports.Period.Summary <- data.Exports.Period.Summary.Annual %>%
  group_by(schema.Place,schema.latitude,schema.longitude, commodity, unit) %>%
  summarise(quantity = mean(quantity))

write.table(data.Exports.Period.Summary.Annual, paste("csv/summary/export-statistics_", period.String ,".csv", sep = ""), row.names = F, quote = T , sep = ",")



# 2. plot: all layers can be stored as variables!
## simple  map; use geom_polygon in ggplot2 to map dataframes
map.Base <- ggplot() +
  labs(x="", y="",
       caption = "Till Grallert, CC BY-SA 4.0")+ # provides title, subtitle, x, y, caption
  geom_polygon(data = map_data("world"), aes(x=long, y = lat, group = group),
               #fill = "#E8E8E8", 
               fill = "#8290C1",
               #color = "#B7B7B7", 
               color = "#48417D",
               alpha = 0.6) + 
  coord_fixed(1.3)+ # fixes the relationship/aspect ratio between coordinates
  guides(fill=FALSE)  # do this to leave off the color legend
map.Base

# specify text sizes
# in themes size is measured in px
size.Base.Mm = 7
# font sizes are measured in mm
size.Base.Px = (5/14) * size.Base.Mm

# specify viewports / zoom levels
# all data points
viewport.Events.All <- c(coord_fixed(xlim = c(max(data.Events.FoodRiots.Period$schema.longitude)+1, 
    min(data.Events.FoodRiots.Period$schema.longitude) -1),  
  ylim = c(max(data.Events.FoodRiots.Period$schema.latitude), 
    min(data.Events.FoodRiots.Period$schema.latitude)), ratio = 1.3))
# Middle East 
viewport.ME <- c(coord_fixed(xlim = c(22, 46),  ylim = c(28, 42), ratio = 1.3))
viewport.Events.Levant <- c(coord_fixed(xlim = c(max(data.Events.FoodRiots.Period.Levant$schema.longitude)+1, 
    min(data.Events.FoodRiots.Period.Levant$schema.longitude) -1),  
  ylim = c(max(data.Events.FoodRiots.Period.Levant$schema.latitude), 
    min(data.Events.FoodRiots.Period.Levant$schema.latitude)), ratio = 1.3))


# variable to store the locations of events as points
geom.Events.FoodRiots <- c(geom_point(data = data.Events.FoodRiots.Period.Summary, 
    aes(x = schema.longitude, y= schema.latitude),
    size = data.Events.FoodRiots.Period.Summary$number.of.events,
    shape = 21, stroke = 2,
    #color = "#FEEE00",
    color = "#F2D902", fill = "#FEFDB2", 
    alpha = 0.5))
geom.Events.FoodRiots.Levant <- c(geom_point(data = data.Events.FoodRiots.Period.Levant.Summary, 
  aes(x = schema.longitude, y= schema.latitude),
  size = data.Events.FoodRiots.Period.Levant.Summary$number.of.events,
  shape = 21, stroke = 2,
  #color = "#FEEE00",
  color = "#F2D902", fill = "#FEFDB2", 
  alpha = 0.5))
geom.Exports <- c(geom_point(data = data.Exports.Period.Summary, 
  aes(x = schema.longitude, y= schema.latitude, colour = commodity, size = quantity),
  #size = data.Exports.Summary$quantity/1000,
  shape = 21, stroke = 2,
  #color = "#F2D902", 
  #fill = "#FEFDB2", 
  alpha = 0.8))

# variable to store the labels for locations
geom.FoodRiots.Labels <- c(geom_text(data = data.Events.FoodRiots.Period.Summary, 
   aes(x = schema.longitude, y = schema.latitude, 
       label = ifelse(number.of.events > 0,paste(as.character(schema.Place),":",number.of.events),''),
       hjust = -0.1, vjust = 0), 
   color = "#000426", check_overlap = FALSE, size = 1.8 * size.Base.Px))

# variables for saving the plots
width.Plot <- 600
height.Plot <- 200
dpi.Plot <- 300
units.Plot <- "mm"

# generate final map: Food riots
map.FoodRiots.All <- map.Base + 
  geom.Events.FoodRiots +
  geom.FoodRiots.Labels +
  labs(title = "Food riots",
       subtitle = paste("between", year(date.Start), "and", year(date.Stop))) + 
  viewport.Events.All
map.FoodRiots.All

ggsave(filename = paste("maps/map_food-riots-", period.String ,".png", sep = ""), 
       plot = map.FoodRiots.All,
       units = units.Plot , height = height.Plot, width = height.Plot, dpi = dpi.Plot)

map.FoodRiots.Levant <- map.Base + 
  geom.Events.FoodRiots.Levant +
  geom.FoodRiots.Labels +
  labs(title = "Food riots in Bilād al-Shām",
       subtitle = paste("between", year(date.Start), "and", year(date.Stop))) + 
  viewport.Events.Levant
map.FoodRiots.Levant

ggsave(filename = paste("maps/map_food-riots-", period.String ,"_levant.png", sep = ""), 
       plot = map.FoodRiots.Levant,
       units = units.Plot , height = height.Plot, width = height.Plot, dpi = dpi.Plot)

# map of exports
map.Exports <- map.Base +
  labs(title = "Exports of cereals",
       subtitle = paste("Annual averages between", year(date.Start), "and", year(date.Stop)))+
  geom.Exports +
  viewport.ME
map.Exports

ggsave(filename = paste("maps/map_exports-", period.String ,"_levant.png", sep = ""), 
       plot = map.Exports,
       units = units.Plot , height = height.Plot, width = height.Plot, dpi = dpi.Plot)

# add data table to plot
theme.table <- ttheme_minimal(base_size = size.Base.Mm)
tbl <- tableGrob(data.Muqtabas.Bylines.Locations.Summary.1,
                 cols = ,
                 rows=NULL, 
                 theme = theme.table)
tbl.1 <- ggtexttable(data.Muqtabas.Bylines.Locations.Summary.1, rows = NULL, 
                     theme = theme.table)

# arrange plots with gridExtra packa

grid.arrange(arrangeGrob(map.Muqtabas.Bylines.ME, tbl, ncol = 2))
grid.arrange(tbl)
grid.arrange(map.Muqtabas.Bylines.ME, tbl, ncol = 2)
grid.arrange(map.Muqtabas.Bylines.ME, tbl,
             nrow=2, ncol = 2, 
             as.table=F,
             heights=c(1,1))

# arrange plots with cowplot() package

ggdraw() +
  draw_plot(map.Muqtabas.Bylines.ME, x = 0, y = 0, width = 0.6, height = 1) +
  draw_plot(tbl, x = 0.7, y = 0, width = 0.3, height = 1)

## using ggmap
# view port
viewport.1 <- make_bbox(lon = data.Events$schema.longitude, schema.latitude = data.Events$schema.latitude, f = .1)
# First get the map. By default it gets it from Google.  I want it to be a satellite map
map.Base <- get_map(location = viewport.1, maptype = "terrain-background", source = "osm", color = "bw")
ggmap(viewport.1)
