# This R script plots data from data frames generated by `trade_process-data.R`

# Remember it is good coding technique to add additional packages to the top of your script 
library(anytime) # for working with dates
library(scales)   # to access breaks/formatting functions
## tidyverse
library(tidyverse) # load the tidyverse, which includes dplyr, tidyr and ggplot2
library(lubridate) # for working with dates
library(ggrepel)
library(ggthemes) # install themes for ggplots
library(gridExtra) # add graphical objects (grob) to ggplot
library(cowplot) # to arrange plots on a canvas
library(plotly) # interactive plots based on ggplot
#library(readr) # for reading data
# mapping packages
library(sp)
library(rgdal)
#library(geojsonio)
library(maps)  # contains outliens of continents, countries etc. Higher resolution is available from mapdata
library(ggmap)
library(maptools)
# enable unicode
Sys.setlocale("LC_ALL", "en_US.UTF-8")
# set a general theme for all ggplots
theme_set(theme_bw())

# set a working directory
setwd("/BachCloud/BTSync/FormerDropbox/FoodRiots/food-riots_data") #Volumes/Dessau HD/

# read / load data
load("rda/trade_exports.rda") # data.Exports

  
# specify period to be mapped / plotted
## function to create subsets for periods
func.Period.Date <- function(f,x,y){f[f$schema.date >= x & f$schema.date <= y,]}
date.Start <- anydate("1855-01-01")
date.Stop <- anydate("1916-12-31")
data.Exports.Period <- func.Period.Date(data.Exports, date.Start, date.Stop)

## Exports by location
data.Exports.Period.Summary.Annual <- data.Exports.Period %>%
  group_by(schema.Place,schema.latitude,schema.longitude, schema.date, commodity, unit, currency) %>%
  summarise(quantity = mean(quantity), # provides the quantity per location, per date, per commodity, per unit and per currency
            value = mean(value)) %>% # same for value
  arrange(schema.Place)
data.Exports.Period.Summary <- data.Exports.Period.Summary.Annual %>%
  group_by(schema.Place,schema.latitude,schema.longitude, commodity, unit) %>%
  summarise(quantity = mean(quantity))

write.table(data.Exports.Period.Summary.Annual, paste("csv/summary/export-statistics_", period.String ,".csv", sep = ""), row.names = F, quote = T , sep = ",")

# variable for period as string
period.String <- paste(year(date.Start),"-",year(date.Stop),sep = "")

# specify a geographic region
## Bilād al-Shām
location.Levant <- c('Acre','Aleppo','Baʿbdā','Beirut','Bayrūt','Damascus','Haifa',
                     'Hama','Hebron','Homs','Jaffa','Jerusalem','Nablus','Latakia','Tripoli','Syria')

# 2. plot: all layers can be stored as variables!
## simple  map; use geom_polygon in ggplot2 to map dataframes
map.Base <- ggplot() +
  labs(x="", y="",
       caption = "Till Grallert, CC BY-SA 4.0")+ # provides title, subtitle, x, y, caption
  geom_polygon(data = map_data("world"), aes(x=long, y = lat, group = group),
               #fill = "#E8E8E8", 
               fill = "#8290C1",
               #color = "#B7B7B7", 
               color = "#48417D",
               alpha = 0.6) + 
  coord_fixed(1.3)+ # fixes the relationship/aspect ratio between coordinates
  guides(fill=FALSE)  # do this to leave off the color legend

# specify text sizes
# in themes size is measured in px
size.Base.Mm = 7
# font sizes are measured in mm
size.Base.Px = (5/14) * size.Base.Mm

# specify viewports / zoom levels
# all data points
viewport.Trade.All <- c(coord_fixed(xlim = c(max(data.Exports.Period$schema.longitude)+1, 
    min(data.Exports.Period$schema.longitude) -1),  
  ylim = c(max(data.Exports.Period$schema.latitude), 
    min(data.Exports.Period$schema.latitude)), ratio = 1.3))
# Middle East 
viewport.ME <- c(coord_fixed(xlim = c(22, 46),  ylim = c(28, 42), ratio = 1.3))


# variable to store the locations of events as points
geom.Exports <- c(geom_point(data = data.Exports.Period, 
  aes(x = schema.longitude, y= schema.latitude, colour = commodity, size = quantity),
  #size = data.Exports.Summary$quantity/1000,
  shape = 21, stroke = 2,
  #color = "#F2D902", 
  #fill = "#FEFDB2", 
  alpha = 0.8))

# variable to store the labels for locations

# variables for saving the plots
width.Plot <- 600
height.Plot <- 200
dpi.Plot <- 300
units.Plot <- "mm"


# map of exports
map.Exports <- map.Base +
  labs(title = "Exports of cereals",
       subtitle = paste("Annual averages between", year(date.Start), "and", year(date.Stop)))+
  geom.Exports +
  viewport.ME
map.Exports

ggsave(filename = paste("maps/map_exports-", period.String ,"_levant.png", sep = ""), 
       plot = map.Exports,
       units = units.Plot , height = height.Plot, width = height.Plot, dpi = dpi.Plot)
